import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";
import LangOption from "../components/LangOption";

export default function Home() {
  const router = useRouter();

  const { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Multi Language</title>
        <meta
          name="description"
          content="Generated by Omar Alkahdery Multi Language App"
        />
        <link
          rel="icon"
          href="https://avatars.githubusercontent.com/u/85066587?v=4"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("common:about")} </h1>
      </main>
    </div>
  );
}
