import Head from "next/head";
import styles from "../styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";

export default function Home() {
  const { t, lang } = useTranslation();
  let style;
  lang === "ar" ? (style = { direction: "rtl", textAlign: "right" }) : null;
  return (
    <div>
      <Head>
        <title>Multi Language</title>
        <meta
          name="description"
          content="Generated by Omar Alkahdery Multi Language App"
        />
        <link
          rel="icon"
          href="https://avatars.githubusercontent.com/u/85066587?v=4"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("common:title")} </h1>
        <br />
        <p className={styles.p} style={style}>
          {t("common:variable-example")}
        </p>
        {
          <h3>
            {t("common:prev-language", {
              lang: t(`common:language-name-${lang}`),
            })}{" "}
          </h3>
        }
      </main>
    </div>
  );
}
